apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: spinnaker
resources:
- base


configMapGenerator:
- name: gate
  behavior: merge
  files:
  - gate-redis=redis.yml

replacements:
- source:
    kind: Deployment
    name: gate
  targets:
  - select:
      kind: Deployment
      name: gate
    fieldPaths:
    - spec.template.spec.containers.[name=gate].env.[name=SPRING_PROFILES_ACTIVE].value
    options:
      delimiter: ','
      create: true
      index: 2

patchesStrategicMerge:
- patches/gate-configmap.yml
- patches/igor-configmap.yml
- patches/rosco-configmap.yml

# patches:
# - target:
#     kind: Deployment
#     name: (gate|igor|rosco)
#   path: monitoring/patches/shared/sidecar.yml

