apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: spinnaker
resources:
- base

patchesStrategicMerge:
- patches/gate-configmap.yml
- patches/igor-configmap.yml
- patches/rosco-configmap.yml
