apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yml
- statefulset.yml
- service.yml
commonLabels:
  app.kubernetes.io/name: mariadb

# TODO: figure out why init.sh gets \n's instead of block like config.sh - `init.sh: |`
# configMapGenerator:
# - files:
#   - config.cnf
#   - init.sh
#   name: mariadb
