apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: DECK_HOST
          value: 0.0.0.0
        - name: DECK_PORT
          value: "9000"
        envFrom:
          - configMapRef:
              name: deck-env
        image: us-docker.pkg.dev/spinnaker-community/docker/deck:latest
        name: deck
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 9000
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: all-in-one
          mountPath: "/opt/spinnaker/config"
          readOnly: true
      # TODO:
      # securityContext:
      #   runAsUser: 10111
      #   runAsGroup: 10111
      #   runAsNonRoot: true
      #   fsGroup: 10111
      volumes:
      - name: all-in-one
        projected:
          sources:
          - configMap:
              name: deck
