apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayenta
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: us-docker.pkg.dev/spinnaker-community/docker/kayenta:latest
        name: kayenta
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: all-in-one
          mountPath: "/opt/spinnaker/config"
          readOnly: true
      securityContext:
        runAsUser: 10111
        runAsGroup: 10111
        runAsNonRoot: true
        fsGroup: 10111
      terminationGracePeriodSeconds: 720
      volumes:
      - name: all-in-one
        projected:
          sources:
          - configMap:
              name: spinnaker
              items:
              - key: spinnaker-local.yml
                path: spinnaker-local.yml
          - configMap:
              name: kayenta
              items:
              - key: kayenta-local.yml
                path: kayenta-local.yml
