apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
commonLabels:
  app.kubernetes.io/name: kayenta
configMapGenerator:
- name: kayenta
  files:
  - ./kayenta-local.yml
