apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
commonLabels:
  app.kubernetes.io/name: igor
configMapGenerator:
- name: igor
  files:
  - ./igor-local.yml
