apiVersion: v1
kind: ConfigMap
metadata:
  name: orca
data:
  orca-mariadb.yml: |
    sql:
      enabled: true
      connectionPool:
        jdbcUrl: jdbc:mysql://mariadb:3306/orca
        user: orca_service
        password: ${ORCA_MARIADB}
        connectionTimeout: 5000
        maxLifetime: 30000
        # MariaDB-specific:
        maxPoolSize: 50
      migration:
        jdbcUrl: jdbc:mysql://mariadb:3306/orca
        user: orca_migrate
        password: ${ORCA_MARIADB}

    # Ensure we're only using SQL for accessing execution state
    executionRepository:
      sql:
        enabled: true
      redis:
        enabled: false

    # Reporting on active execution metrics will be handled by SQL
    monitor:
      activeExecutions:
        redis: false

    # Use SQL for Orca's work queue
    # Settings from Netflix and may require adjustment for your environment
    # Only validated with AWS Aurora MySQL 5.7
    # Please PR if you have success with other databases
    keiko:
      queue:
        sql:
          enabled: true
        redis:
          enabled: false

    queue:
      zombieCheck:
        enabled: true
      pendingExecutionService:
        sql:
          enabled: true
        redis:
          enabled: false
