apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
commonLabels:
  app.kubernetes.io/name: front50
configMapGenerator:
- name: front50
  files:
  - ./front50-local.yml
