apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../base
nameSuffix: -ro-deck
commonLabels:
  app.kubernetes.io/name: clouddriver-ro-deck
patchesStrategicMerge:
- profile.yml
